export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMON_ID = 'GET_POKEMON_ID';
export const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const CREATE_POKEMON = 'CREATE_POKEMON';
export const GET_POKEMON_API = 'GET_POKEMON_API';
export const GET_POKEMON_DB = 'GET_POKEMON_DB';
export const SORT_NAME = 'SORT_NAME';
export const SORT_ATTACK = 'SORT_ATTACK';
export const FILTER_TYPE = 'FILTER_TYPE';
export const FILTER_POKEMON = 'FILTER_POKEMON';

